### ISSUE TITLE
No data preview for multiple datasets

### ISSUE THREAD

**Issue by ruvolo** [ColFusion/ColfusionWeb#51]
The following datasets do not seem to be able to display a  data preview.  The system seems to be having some problems processing the data.  

Silver production of Durango, Mexico, 1599-1813
Export Statistics for Dahomey, 1915-1960
Import Statistics for Dahomey, 1889-1914
Silver production of Chile, 1762-1815
Silver production of Chihuahua, Mexico, 1785-1814
Silver production of Carangas, Peru, 1652-1803
Silver production of Bolanos, Mexico, 1753-1810

**Comment by Drwenski** [comment]
I've noticed the same thing with datasets I've uploaded with multiple (data) sheets, i.e. sheets with more than just a metadata sheet and a single datatable.

**Comment by EvgenyKarataev** [comment]
Thanks for creating the issues. I will have a look at all datasets on
colfusion that don't show data preview.

Best Regards,
Evgeny Karataev

**Comment by ruvolo** [comment]
Thanks, Evgeny.  We have a visiting scholar who we will be meeting with tomorrow.  His focus is on historical silver flows, so we would love to show him some of the data in Colfusion if possible.

David Ruvolo
Research Project Manager, CHIA Project
Managing Editor, Journal of World-Historical Information
World History Center
3900 Wesley W. Posvar Hall
University of Pittsburgh
Pittsburgh, PA 15260
dar133@pitt.edumailto:dar133@pitt.edu
412-624-8726

**Comment by EvgenyKarataev** [comment]
I am looking at the first dataset that doesn't show a data preview (Silver production of Durango, Mexico, 1599-1813) and the reason why the data preview is not show is because one of the variables/column name/header has a trailing space (particularly the column 'Pesos '). This issue need to be fixed as I filed a bug (ColFusion/ColfusionServer#57).

I will try to fix the data preview for the data set without the need to resubmit it.

**Comment by EvgenyKarataev** [comment]
Seems like Silver production of Durango, Mexico, 1599-1813 now has data preview.

**Comment by EvgenyKarataev** [comment]
The "Export Statistics for Dahomey, 1915-1960" dataset doesn't have a data preview for the same reasons. column name 'Export valuea accounted for '  has a trailing space at the end. Currently system fails because of that, need to fix it ASAP. Will try to make the dataset show data preview without resubmission.

**Comment by EvgenyKarataev** [comment]
Done with "Export Statistics for Dahomey, 1915-1960", will try to fix other datasets later as well. @ruvolo and @Drwenski at least for now, could you please make sure the headers/variables in the excel files has not trailing spaces (before or after) for new datasets.

**Comment by EvgenyKarataev** [comment]
Made data preview work for Import Statistics for Dahomey, 1889-1914 datasets, however there is a bigger issue of variables/headers being repeated several time in the dataset. Send email to @ruvolo about it.

**Comment by EvgenyKarataev** [comment]
Fixed 'Silver production of Chile, 1762-1815' dataset. It failed before due to the empty column name.

**Comment by EvgenyKarataev** [comment]
Fixed 'Silver production of Chihuahua, Mexico, 1785-1814', failed due to the trailing space at the end of the Pesos variable.

**Comment by EvgenyKarataev** [comment]
Fixed 'Silver production of Carangas, Peru, 1652-1803', failed due to the trailing space at the end of the Pesos variable.

**Comment by EvgenyKarataev** [comment]
Fixed 'Silver production of Bolanos, Mexico, 1753-1810', not exactly sure what went wrong. Did somebody try to edit the table through openrefine?

**Comment by ruvolo** [comment]
I was tinkering around on OpenRefine on, I believe, this dataset, but I didn't think I saved anything.  
It is definitely possible that I'm the culprit.

**Comment by EvgenyKarataev** [comment]
that's fine. Open refine doesn't work if we do any structural changes (e.g.
rename, add, delete a column), but for the data it should work.

Best Regards,
Evgeny Karataev
